
internationalEvents = [
  {
    "conference": "Labor and Employment Relations Association Annual Meeting",
    "host": "Labor and Employment Relations Association",
    "theme": "Bridging the Divide: Tripartite Solutions for a Changing World",
    "location": "Minneapolis, Minnesota, United States",
    "date": "28–31 May 2026",
    "paper": "Regulating the Algorithm: Rethinking Labour Rights and Collective Bargaining in the Age of Artificial Intelligence",
    "authors": "Nancy Nzom",
    "year": "2026",
    "summary": "This research examines how algorithmic management is transforming labour governance and collective bargaining frameworks. It explores regulatory approaches aimed at protecting workers in artificial intelligence-driven workplaces.",
  },
  {
    "conference": "Americans with Disabilities Act and Universal Design Conference",
    "host": "Syracuse University College of Law",
    "theme": "Americans with Disabilities Act and Universal Design: Global Legacy and Potential in Higher Education",
    "location": "Syracuse, New York, United States",
    "date": "10 April 2026",
    "paper": "Artificial Intelligence for Inclusion: Operationalising Universal Design for Learning in African Universities",
    "authors": "Nancy Nzom",
    "year": "2026",
    "summary": "This research explores how artificial intelligence can strengthen accessibility and inclusive education in African universities through the framework of Universal Design for Learning.",
  },
  {
    "conference": "Agriculture and Food Policy Spring Symposium",
    "host": "University of St. Thomas School of Law",
    "theme": "",
    "location": "Virtual Symposium",
    "date": "10 April 2026",
    "paper": "Joint Presentation",
    "authors": "Nancy Nzom & Daniel Moses Eyyazo",
    "year": "2026",
    "summary": "This research examines regulatory and governance issues within agricultural and food policy systems, including institutional ownership of farmland and broader policy implications for food security and rural development.",
  },
  {
    "conference": "Development Studies Association Annual Conference",
    "host": "University College Dublin",
    "theme": "Reimagining Development: Power, Agency and Futures in an Uncertain World",
    "location": "Dublin, Ireland",
    "date": "8–11 July 2026",
    "paper": "Reimagining Labour Regulation in the Age of Algorithmic Management: Power, Agency and Job Quality in the Global South",
    "authors": "Nancy Nzom & Daniel Moses Eyyazo",
    "year": "2026",
    "summary": "This research analyses the implications of algorithmic management for labour regulation and job quality in the Global South and proposes legal and institutional frameworks aimed at protecting workers in digitally managed workplaces.",
  },
  {
    "conference": "Human Resource Management and Employment Relations Conference",
    "host": "King's Business School",
    "theme": "Shaping the Future of Work",
    "location": "London, United Kingdom",
    "date": "2026",
    "paper": "Artificial Intelligence as Workplace Infrastructure: Accessibility, Algorithmic Management and Employment Protection",
    "authors": "Nancy Nzom",
    "year": "2026",
    "summary": "This research analyses how artificial intelligence is reshaping workplace governance and employment protection frameworks and evaluates regulatory approaches for ensuring fairness, accessibility and accountability in technology-driven workplaces.",
  },
]

nigerianEvents = [
  {
    "conference": "Hybrid International Conference on Sustainable Development Goals, Contemporary Challenges and the Role of Law",
    "host": "Faculty of Law, University of Nigeria",
    "theme": "",
    "location": "Enugu, Nigeria",
    "date": "24 June 2025",
    "paper": "Labour Disputes, Legal Frameworks and the Sustainable Development Goals: Strengthening Public Sector Accountability through Effective Dispute Resolution in Nigeria",
    "authors": "Nancy Nzom",
    "year": "2025",
    "summary": "This research examines the role of effective dispute resolution mechanisms in strengthening labour governance and institutional accountability in Nigeria's public sector while supporting the achievement of the Sustainable Development Goals.",
  },
]